apiVersion: v2
name: pagopa-tech-support-api
description: Technical support api
type: application
version: "0.75.0"
appVersion: "1.2.22-1-PIDM-1117-status-recovery"
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
