apiVersion: v2
name: pagopa-tech-support-api
description: Technical support api
type: application
version: "0.68.0"
appVersion: "1.2.16"
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
